### ISSUE TITLE
大佬 召回模型什么时候开源呀？一直在等 急哭了！

### ISSUE THREAD

**Issue by tcandzq** [RainFung/Tianchi-AntaiCup-International-E-commerce-Artificial-Intelligence-Challenge#7]
一直想看看你们召回的方案 苦苦等待 希望可以开源给我们学习！谢谢大佬！

**Comment by RainFung** [comment]
不好意思，工作比较忙，没时间更新，要不你留个联系方式吧，我回头联系你。

**Comment by tcandzq** [comment]
好的 我的微信：TC18895612891 邮箱：18895612891@163.com 谢谢大佬~

**Comment by Paipaic** [comment]
> 不好意思，工作比较忙，没时间更新，要不你留个联系方式吧，我回头联系你。

大佬您好，很希望能学习一下你们的召回模型，但是部分代码一直没有开源。如果您有方便的话，可以把完整的代码发给我一份嘛，万分感激！我的邮箱879865704@qq.com，再次感谢！

**Comment by IceLocke** [comment]
> 不好意思，工作比较忙，没时间更新，要不你留个联系方式吧，我回头联系你。

您好，这段时间在通过这个比赛学习，希望能参考一下你们的代码，但是召回模型还是不在 repo 中。如果您闲时方便的话，可以麻烦您把召回模型的代码发给我吗？我的邮箱是 linghugong@link.cuhk.edu.cn，谢谢！
